"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file if it exists
env_path = BASE_DIR.parent / '.env'
if env_path.exists():
    load_dotenv(env_path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-(@ma8e4m8eizu1)o61kj#kzqhgtl9vsew!yhi(4^g#qzts3q3(')

# SECURITY WARNING: don't run with debug turned on in production!
# Default to False in production
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',') if os.getenv('DJANGO_ALLOWED_HOSTS') else []

# Honor the 'X-Forwarded-Proto' header for request.is_secure()
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# LLM provider keys — read from the environment. pydantic-ai resolves these
# from os.environ directly (GEMINI_API_KEY for the `google` provider — the
# GoogleProvider falls back to GEMINI_API_KEY when GOOGLE_API_KEY is unset —
# and ANTHROPIC_API_KEY for anthropic models), so the chatbot picks them up
# without further wiring.
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY', '')

CSRF_TRUSTED_ORIGINS = [
    'https://datagov.welcomd.com',
    'http://datagov.welcomd.com',
]

if os.getenv('DJANGO_ALLOWED_HOSTS'):
    hosts = os.getenv('DJANGO_ALLOWED_HOSTS').split(',')
    for host in hosts:
        host = host.strip()
        if host:
            CSRF_TRUSTED_ORIGINS.append(f"https://{host}")
            CSRF_TRUSTED_ORIGINS.append(f"http://{host}")


SLACK_CLIENT_ID = os.getenv('SLACK_CLIENT_ID', '')
SLACK_CLIENT_SECRET = os.getenv('SLACK_CLIENT_SECRET', '')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django_q',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'django_filters',
    'tailwind',
    'theme',
    'catalog',
]

TAILWIND_APP_NAME = 'theme'
INTERNAL_IPS = [
    "127.0.0.1",
]
NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

Q_CLUSTER = {
    'name': 'WelcomeDataCatalogORM',
    'workers': 4,
    'recycle': 500,
    'timeout': 3600, # Large timeout to allow heavy Fabric API extractions (30m)
    'retry': 3700,   # Must be > timeout to prevent duplicate runs
    'compress': True,
    'save_limit': 250,
    'queue_limit': 500,
    'cpu_affinity': 1,
    'label': 'Django Q',
    'orm': 'default'
}

# Cache backend — must be shared across all OS processes (web server + Django Q worker).
# LocMemCache (Django's default) is per-process and would make cross-process cache
# writes (e.g. chat status updates from the worker) invisible to the web server.
# DatabaseCache is the safest option for single-database deployments with no Redis.
# After updating this setting, run:  python manage.py createcachetable
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache_table',
        'TIMEOUT': 600,   # 10 minutes — long enough to survive a slow agent run
        'OPTIONS': {
            'MAX_ENTRIES': 2000,
        }
    }
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'catalog.middleware.UserActivityMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = DEBUG

# Add security settings for production.
# Secure cookies require HTTPS. They're gated on SECURE_COOKIES (defaults to on
# whenever DEBUG is off) so a production-like stack (DEBUG=False + Postgres) can
# still be run over plain http://localhost — e.g. the local Docker stack pointed
# at a dumped copy of production — by setting SECURE_COOKIES=False, without
# breaking login (a Secure cookie is never sent over http).
SECURE_COOKIES = os.getenv('SECURE_COOKIES', 'False' if DEBUG else 'True') == 'True'
if not DEBUG:
    # Security Middleware settings
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # If your app is exclusively served over HTTPS by Cloudflare, these should be True
    SESSION_COOKIE_SECURE = SECURE_COOKIES
    CSRF_COOKIE_SECURE = SECURE_COOKIES
    # Optional: SECURE_SSL_REDIRECT = True

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DEBUG drives the database target:
#   DEBUG=True  -> LOCAL Docker Postgres (the 'db' service; DB_* in backend/.env).
#   DEBUG=False -> PRODUCTION Azure Postgres (PROD_DB_* in backend/.env).
# WARNING: with DEBUG=False the running app — including all ETL writes — talks to
# PRODUCTION. Use DEBUG=True for any local work.
if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'catalog'),
            'USER': os.getenv('DB_USER', 'catalog'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'db'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'OPTIONS': {
                # The local Docker Postgres container serves no SSL, so default to
                # 'disable' (override with DB_SSLMODE if needed).
                'sslmode': os.getenv('DB_SSLMODE', 'disable'),
                'connect_timeout': 10,         # Fail fast on unreachable DB (seconds)
            },
            'CONN_MAX_AGE': 600,
            'CONN_HEALTH_CHECKS': True,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('PROD_DB_NAME', 'postgres'),
            'USER': os.getenv('PROD_DB_USER', 'kingstar'),
            'PASSWORD': os.getenv('PROD_DB_PASSWORD', ''),
            'HOST': os.getenv('PROD_DB_HOST', 'data-operations.postgres.database.azure.com'),
            'PORT': os.getenv('PROD_DB_PORT', '5432'),
            'OPTIONS': {
                # Azure Postgres requires SSL.
                'sslmode': os.getenv('PROD_DB_SSLMODE', 'require'),
                'connect_timeout': 10,         # Fail fast on unreachable DB (seconds)
            },
            # Keep connections alive for 10 minutes (avoids reconnect on every request,
            # but still refreshes before Azure kills idle connections ~30 min).
            'CONN_MAX_AGE': 600,
            # Django 4.1+: verify health of persistent connections before reuse.
            # Prevents "connection timeout expired" on stale connections (common with
            # Azure PostgreSQL which aggressively closes idle connections).
            'CONN_HEALTH_CHECKS': True,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# User-uploaded files (e.g. the per-organization branding icon). Served by
# Django in DEBUG (see config/urls.py) and by nginx `/media/` in production;
# the Next.js dev server proxies `/media/*` here so the SPA stays single-origin.
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'catalog.CustomUser'

AUTHENTICATION_BACKENDS = [
    'catalog.backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/login/'
LOGOUT_REDIRECT_URL = '/login/'
