# Generated by Django 6.0.3 on 2026-04-24 14:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_type', models.CharField(choices=[('bigquery', 'Google BigQuery')], default='bigquery', max_length=50)),
                ('name', models.CharField(default='BigQuery', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('bq_project_id', models.CharField(blank=True, max_length=255, null=True)),
                ('bq_dataset_id', models.CharField(blank=True, max_length=255, null=True)),
                ('bq_service_account_json', models.TextField(blank=True, help_text='Full GCP service account JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slack_bot_token', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_color', models.CharField(blank=True, default='#00cf95', max_length=50)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='organizations/icons/')),
                ('powerbi_tools_enabled', models.BooleanField(default=False, help_text='Allow the AI Assistant to execute live commands against the PowerBI REST API.')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.department')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='catalog.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DestinationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('manual', 'Manual Only'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom Cron')], default='manual', max_length=20)),
                ('cron_expression', models.CharField(blank=True, help_text='e.g. 0 2 * * *', max_length=100, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='catalog.integrationdestination')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('log_output', models.TextField(blank=True, null=True)),
                ('triggered_by', models.CharField(default='manual', help_text='manual or scheduler', max_length=50)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_logs', to='catalog.integrationdestination')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('powerbi_fabric', 'PowerBI / Microsoft Fabric API'), ('csv_upload', 'CSV Upload'), ('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('snowflake', 'Snowflake'), ('dbt', 'dbt (Data Build Tool)')], default='powerbi_fabric', max_length=50)),
                ('name', models.CharField(default='PowerBI Fabric', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=500, null=True)),
                ('workspace_ids', models.JSONField(blank=True, default=list)),
                ('github_repo_url', models.URLField(blank=True, help_text='GitHub repository URL (e.g. https://github.com/org/dbt-project)', max_length=500, null=True)),
                ('github_token', models.CharField(blank=True, help_text='GitHub Personal Access Token (for private repos)', max_length=500, null=True)),
                ('github_branch', models.CharField(blank=True, default='main', help_text='Branch to pull artifacts from', max_length=100, null=True)),
                ('dbt_manifest_path', models.CharField(blank=True, default='target/manifest.json', help_text='Path to manifest.json in the repository', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='catalog.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationHook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hook_type', models.CharField(choices=[('slack', 'Slack'), ('slack_alerts', 'Slack Alerts')], default='slack', max_length=50)),
                ('name', models.CharField(default='Slack', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('slack_bot_token', models.CharField(blank=True, max_length=500, null=True)),
                ('slack_channel', models.CharField(blank=True, max_length=255, null=True)),
                ('slack_alerts_channel', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hooks', to='catalog.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='integrationdestination',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='catalog.organization'),
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='catalog.organization'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='catalog.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='catalog.department')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owners', to='catalog.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SourceRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('log_output', models.TextField(blank=True, null=True)),
                ('triggered_by', models.CharField(default='manual', help_text='manual or scheduler', max_length=50)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_logs', to='catalog.integrationsource')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('manual', 'Manual Only'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom Cron')], default='manual', max_length=20)),
                ('cron_expression', models.CharField(blank=True, help_text='e.g. 0 2 * * *', max_length=100, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='catalog.integrationsource')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_measures', models.IntegerField()),
                ('unused_measures', models.IntegerField()),
                ('total_columns', models.IntegerField()),
                ('unused_columns', models.IntegerField()),
                ('total_reports', models.IntegerField()),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summaries', to='catalog.organization')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('node_id', models.CharField(max_length=512, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('group', models.CharField(blank=True, max_length=50, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_nodes', to='catalog.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['group'], name='catalog_net_group_039608_idx'), models.Index(fields=['name'], name='catalog_net_name_fd3f14_idx')],
            },
        ),
        migrations.CreateModel(
            name='NetworkEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=512)),
                ('target', models.CharField(max_length=512)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_edges', to='catalog.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['source'], name='catalog_net_source_54a439_idx'), models.Index(fields=['target'], name='catalog_net_target_3fa985_idx')],
                'unique_together': {('source', 'target')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'organization')},
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('access_level', models.CharField(choices=[('read_only', 'Read Only'), ('read_write', 'Read & Write')], default='read_only', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='catalog.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('lineage_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('item_type', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('workspace_id', models.CharField(blank=True, max_length=255, null=True)),
                ('workspace_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dataset_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dataset_name', models.CharField(blank=True, max_length=255, null=True)),
                ('table_name', models.CharField(blank=True, max_length=255, null=True)),
                ('datatype', models.CharField(blank=True, max_length=50, null=True)),
                ('column_type', models.CharField(blank=True, max_length=50, null=True)),
                ('expression', models.TextField(blank=True, null=True)),
                ('formatstring', models.CharField(blank=True, max_length=255, null=True)),
                ('is_unused', models.BooleanField(default=False)),
                ('connected_reports', models.IntegerField(default=0)),
                ('connected_report_pages', models.IntegerField(default=0)),
                ('connected_visuals', models.IntegerField(default=0)),
                ('connected_measures', models.IntegerField(default=0)),
                ('connected_columns', models.IntegerField(default=0)),
                ('connected_tables', models.IntegerField(default=0)),
                ('connected_reports_json', models.JSONField(blank=True, default=list)),
                ('deleted', models.BooleanField(default=False)),
                ('web_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('DEPRECATED', 'Deprecated'), ('ATTENTION', 'Attention')], default='UNVERIFIED', max_length=20)),
                ('custom_description', models.TextField(blank=True, null=True)),
                ('service', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='catalog.category')),
                ('ownership_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.department')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='catalog.organization')),
                ('ownership_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_items', to='catalog.owner')),
                ('steward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stewarded_items', to='catalog.owner')),
            ],
            options={
                'ordering': ['item_name'],
                'indexes': [models.Index(fields=['item_id'], name='catalog_ite_item_id_fe8893_idx'), models.Index(fields=['item_type'], name='catalog_ite_item_ty_617364_idx'), models.Index(fields=['workspace_name'], name='catalog_ite_workspa_254f09_idx'), models.Index(fields=['is_unused'], name='catalog_ite_is_unus_122433_idx'), models.Index(fields=['deleted'], name='catalog_ite_deleted_96b874_idx'), models.Index(fields=['dataset_name'], name='catalog_ite_dataset_1882c5_idx'), models.Index(fields=['organization'], name='catalog_item_org_idx')],
            },
        ),
    ]
