# Generated by Django 6.0.3 on 2026-04-24 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('current_stage', models.CharField(choices=[('pending', 'Pending'), ('init', 'Initializing'), ('sources', 'Running Sources'), ('final', 'Final Step'), ('destinations', 'Running Destinations'), ('done', 'Done')], default='pending', max_length=20)),
                ('triggered_by', models.CharField(default='manual', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('log_output', models.TextField(blank=True, default='')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_runs', to='catalog.organization')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('manual', 'Manual Only'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom Cron')], default='manual', max_length=20)),
                ('cron_expression', models.CharField(blank=True, max_length=100, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_schedule', to='catalog.organization')),
            ],
        ),
    ]
