# Generated by Django 6.0.3 on 2026-04-24 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_workflow_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='database_name',
            field=models.CharField(blank=True, help_text='Database part of the 3-part FQN (database.schema.table)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='integration_source',
            field=models.ForeignKey(blank=True, help_text='The IntegrationSource that produced this item via ETL', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='catalog.integrationsource'),
        ),
        migrations.AddField(
            model_name='item',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='Catch-all for source-specific metadata: dbt meta, constraints, loader, access level, and any future niche fields.'),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='dbt tags, PowerBI sensitivity labels, etc.'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['service'], name='catalog_item_service_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['integration_source'], name='catalog_item_intsrc_idx'),
        ),
    ]
