# Generated by Django 6.0.3 on 2026-04-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_item_database_name_item_integration_source_item_meta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='column_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='datatype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
