# Generated by Django 6.0.3 on 2026-04-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_integrationsource_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='debug_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='organization',
            name='debug_responses_enabled',
            field=models.BooleanField(default=False, help_text='Append a hardcoded debug section (DAX, BigQuery SQL, tool calls, and timing stats) to every chatbot answer. Tool-call metadata is always persisted to ChatMessage.debug_meta regardless of this flag.'),
        ),
    ]
