# Generated by Django 6.0.3 on 2026-05-05 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_chatmessage_debug_meta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerBIReportUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month bucket (YYYY-MM-01).')),
                ('workspace_id', models.TextField(blank=True, null=True)),
                ('workspace_name', models.TextField(blank=True, null=True)),
                ('report_id', models.TextField(blank=True, help_text='Power BI report GUID. Joins to Item.item_id via the same hash used by the Fabric ETL.', null=True)),
                ('report_name', models.TextField(blank=True, null=True)),
                ('user_email', models.TextField(blank=True, null=True)),
                ('user_display_name', models.TextField(blank=True, null=True)),
                ('platform', models.TextField(blank=True, null=True)),
                ('distribution_method', models.TextField(blank=True, null=True)),
                ('report_page', models.TextField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('integration_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='powerbi_usage', to='catalog.integrationsource')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='powerbi_usage', to='catalog.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['month'], name='pb_usage_month_idx'), models.Index(fields=['workspace_id'], name='pb_usage_ws_idx'), models.Index(fields=['report_id'], name='pb_usage_report_idx'), models.Index(fields=['user_email'], name='pb_usage_user_idx'), models.Index(fields=['organization'], name='pb_usage_org_idx'), models.Index(fields=['integration_source'], name='pb_usage_intsrc_idx')],
            },
        ),
    ]
