# Generated by Django 6.0.3 on 2026-05-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_useractivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='flow_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
