# Generated by Django 6.0.3 on 2026-05-11 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_dataperson_departments_m2m'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pblivequerythread',
            new_name='catalog_pbl_updated_3008b4_idx',
            old_name='catalog_pbl_updated_idx',
        ),
    ]
