# Generated by Django 6.0.3 on 2026-05-11 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_rename_catalog_pbl_updated_idx_catalog_pbl_updated_3008b4_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmembership',
            name='access_level',
        ),
    ]
