# Generated by Django 6.0.3 on 2026-05-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_add_gemini35_flash'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='show_deleted_items',
            field=models.BooleanField(default=False, help_text='When ON, items that no longer exist in the source (soft-deleted by ETL) are still counted and listed in the dashboard and catalog pages. When OFF (default), they are hidden from all views but preserved in the database for history.'),
        ),
    ]
