# Generated by Django 6.0.3 on 2026-06-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_item_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='governancetask',
            name='assignee_role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
