# Generated by Django 6.0.3 on 2026-06-17 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_add_claude_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_key', models.CharField(blank=True, max_length=1100, null=True)),
                ('old_status', models.CharField(blank=True, choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('DEPRECATED', 'Deprecated'), ('ATTENTION', 'Attention')], max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('DEPRECATED', 'Deprecated'), ('ATTENTION', 'Attention')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('item_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to='catalog.itemgroup')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to='catalog.organization')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['item_group', 'changed_at'], name='cat_statuslog_group_idx'), models.Index(fields=['organization', 'changed_at'], name='cat_statuslog_org_idx'), models.Index(fields=['new_status'], name='cat_statuslog_status_idx')],
            },
        ),
    ]
