# Generated by Django 6.0.3 on 2026-06-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_backfill_deprecated_status_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemgroup',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
