# Generated by Django 6.0.3 on 2026-06-17 15:51
#
# Renames the governance status value 'DEPRECATED' -> 'DELETED' (the user-facing
# concept is now "Deleted"). Besides the choices change, the RunPython step
# rewrites every existing row holding the old value across all status columns
# (Item.status, ItemGroup.status, GovernanceTask.trigger_status, and both
# StatusChangeLog status columns) so no stale 'DEPRECATED' survives.

from django.db import migrations, models


def deprecated_to_deleted(apps, schema_editor):
    Item = apps.get_model('catalog', 'Item')
    ItemGroup = apps.get_model('catalog', 'ItemGroup')
    GovernanceTask = apps.get_model('catalog', 'GovernanceTask')
    StatusChangeLog = apps.get_model('catalog', 'StatusChangeLog')
    Item.objects.filter(status='DEPRECATED').update(status='DELETED')
    ItemGroup.objects.filter(status='DEPRECATED').update(status='DELETED')
    GovernanceTask.objects.filter(trigger_status='DEPRECATED').update(trigger_status='DELETED')
    StatusChangeLog.objects.filter(old_status='DEPRECATED').update(old_status='DELETED')
    StatusChangeLog.objects.filter(new_status='DEPRECATED').update(new_status='DELETED')


def deleted_to_deprecated(apps, schema_editor):
    Item = apps.get_model('catalog', 'Item')
    ItemGroup = apps.get_model('catalog', 'ItemGroup')
    GovernanceTask = apps.get_model('catalog', 'GovernanceTask')
    StatusChangeLog = apps.get_model('catalog', 'StatusChangeLog')
    Item.objects.filter(status='DELETED').update(status='DEPRECATED')
    ItemGroup.objects.filter(status='DELETED').update(status='DEPRECATED')
    GovernanceTask.objects.filter(trigger_status='DELETED').update(trigger_status='DEPRECATED')
    StatusChangeLog.objects.filter(old_status='DELETED').update(old_status='DEPRECATED')
    StatusChangeLog.objects.filter(new_status='DELETED').update(new_status='DEPRECATED')


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_item_status_itemgroup_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governancetask',
            name='trigger_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('DELETED', 'Deleted'), ('ATTENTION', 'Attention')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('DELETED', 'Deleted'), ('ATTENTION', 'Attention')], db_index=True, default='UNVERIFIED', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemgroup',
            name='status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('DELETED', 'Deleted'), ('ATTENTION', 'Attention')], default='UNVERIFIED', max_length=20),
        ),
        migrations.AlterField(
            model_name='statuschangelog',
            name='new_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('DELETED', 'Deleted'), ('ATTENTION', 'Attention')], max_length=20),
        ),
        migrations.AlterField(
            model_name='statuschangelog',
            name='old_status',
            field=models.CharField(blank=True, choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('DELETED', 'Deleted'), ('ATTENTION', 'Attention')], max_length=20, null=True),
        ),
        migrations.RunPython(deprecated_to_deleted, deleted_to_deprecated),
    ]
