# Generated by Django 6.0.3 on 2026-06-25 21:07

from django.db import migrations, models


def backfill_kind_level(apps, schema_editor):
    """Classify every pre-existing edge from its node-id prefixes so the new
    columns are populated before reads start filtering on them. Uses the same
    single-source-of-truth classifier the loaders use, in DB-agnostic chunks."""
    from catalog.services.network_classify import classify_node_ids

    Edge = apps.get_model('catalog', 'NetworkEdge')
    batch = []
    BATCH = 5000
    qs = Edge.objects.all().only('id', 'source', 'target', 'kind', 'level')
    for e in qs.iterator(chunk_size=BATCH):
        e.kind, e.level = classify_node_ids(e.source, e.target)
        batch.append(e)
        if len(batch) >= BATCH:
            Edge.objects.bulk_update(batch, ['kind', 'level'])
            batch = []
    if batch:
        Edge.objects.bulk_update(batch, ['kind', 'level'])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_fix_google_provider_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkedge',
            name='kind',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='networkedge',
            name='level',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.RunPython(backfill_kind_level, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='networkedge',
            index=models.Index(fields=['level'], name='catalog_net_level_65a324_idx'),
        ),
        migrations.AddIndex(
            model_name='networkedge',
            index=models.Index(fields=['kind'], name='catalog_net_kind_6de243_idx'),
        ),
    ]
