# Generated by Django 6.0.3 on 2026-06-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0051_organization_assistant_bigquery_dataset_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='chat_timeout_seconds',
            field=models.PositiveIntegerField(default=180, help_text='Maximum seconds the AI Assistant may run per question before the request is aborted with a timeout error (web chat).'),
        ),
    ]
