# Generated by Django 6.0.3 on 2026-06-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0053_consistent_assistant_tool_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricsmap',
            name='public_token',
            field=models.UUIDField(blank=True, db_index=True, editable=False, help_text='Set when public sharing is enabled; the anonymous share-URL key. Null = not shared.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='metricsmap',
            name='public_can_drag',
            field=models.BooleanField(default=True, help_text='Whether anonymous viewers of the shared link may drag nodes (never persisted).'),
        ),
    ]
