"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  ReactFlow,
  Background,
  Controls,
  MiniMap,
  ConnectionMode,
  useNodesState,
  useEdgesState,
  useReactFlow,
  getNodesBounds,
  getViewportForBounds,
} from "@xyflow/react";
import { useQuery } from "@tanstack/react-query";
import { Image as ImageIcon, Maximize } from "lucide-react";
import { api } from "@/lib/api";
import { typeMeta } from "@/lib/metrics-canvas/catalog";
import { fromDoc, decorateEdgeLabel, exportPng, type RfEdge, type RfNode } from "@/lib/metrics-canvas/serialize";
import { emptyDoc, type CanvasGroup, type CanvasMeta, type CanvasNodeData } from "@/lib/metrics-canvas/types";
import { nodeTypes } from "@/components/metrics-canvas/nodes";
import { edgeTypes } from "@/components/metrics-canvas/edges";
import { CanvasInteractionProvider } from "@/components/metrics-canvas/interaction";
import { GroupsOverlay } from "@/components/metrics-canvas/groups-overlay";
import { LoadingState, EmptyState } from "@/components/ui/misc";

const noop = () => {};

/**
 * Public, read-only viewer for a shared metrics map. Rendered at
 * `/share/metrics-map/<token>` for anyone with the link — no login. It reuses
 * the editor's node/edge renderers and group overlay but strips every authoring
 * affordance: no palette, no properties panel, no save/import, no connecting or
 * adding/deleting. Viewers may *drag* nodes around when the owner allows it, but
 * those moves are purely local (no write path) — reloading restores the layout.
 */
export function MetricsCanvasViewer({ token }: { token: string }) {
  const { fitView } = useReactFlow();
  const wrapperRef = useRef<HTMLDivElement>(null);

  const { data, isLoading, isError } = useQuery({
    queryKey: ["metrics-map-public", token],
    queryFn: () => api.metricsMaps.publicGet(token),
    retry: false,
  });

  const [nodes, setNodes, onNodesChange] = useNodesState<RfNode>([]);
  const [edges, setEdges] = useEdgesState<RfEdge>([]);
  const [groups, setGroups] = useState<CanvasGroup[]>([]);
  const [meta, setMeta] = useState<CanvasMeta>(() => emptyDoc().meta);
  const nodesRef = useRef(nodes);
  const groupsRef = useRef(groups);
  nodesRef.current = nodes;
  groupsRef.current = groups;

  const canDrag = data?.public_can_drag ?? true;
  const fontScale = meta.fontScale ?? 1;

  // Drag a group by its label: shift every member node by the same flow-space
  // delta. Ephemeral, like node drags — viewers can rearrange but nothing is
  // saved. Only wired when the owner allows viewer-drag.
  const moveGroupBy = useCallback(
    (groupId: string, dx: number, dy: number) => {
      const g = groupsRef.current.find((gr) => gr.id === groupId);
      if (!g) return;
      const ids = new Set(g.nodeIds);
      setNodes((ns) =>
        ns.map((n) =>
          ids.has(n.id) ? { ...n, position: { x: n.position.x + dx, y: n.position.y + dy } } : n,
        ),
      );
    },
    [setNodes],
  );

  // Hydrate the canvas once the public document arrives.
  useEffect(() => {
    if (!data) return;
    const s = fromDoc(data.graph ?? emptyDoc(data.name));
    setNodes(s.nodes);
    setEdges(s.edges);
    setGroups(s.groups);
    setMeta(s.meta);
    requestAnimationFrame(() => fitView({ padding: 0.2 }));
  }, [data, setNodes, setEdges, fitView]);

  // Render every edge as a "floating" edge (attaches to the facing side of each
  // box) so a shared map looks exactly as clean as the editor.
  const rfEdges = useMemo(
    () => edges.map((e) => ({ ...decorateEdgeLabel(e, fontScale), type: "floating" })),
    [edges, fontScale],
  );
  const interaction = useMemo(() => ({ onLabelCommit: noop, fontScale, readOnly: true }), [fontScale]);

  const onExportPng = useCallback(async () => {
    const el = wrapperRef.current?.querySelector(".react-flow__viewport") as HTMLElement | null;
    if (!el || !nodesRef.current.length) return;
    const bounds = getNodesBounds(nodesRef.current);
    const width = Math.min(2400, Math.max(480, Math.round(bounds.width + 160)));
    const height = Math.min(2000, Math.max(320, Math.round(bounds.height + 160)));
    const vp = getViewportForBounds(bounds, width, height, 0.2, 2, 0.1);
    await exportPng(el, meta.name, {
      width,
      height,
      transform: `translate(${vp.x}px, ${vp.y}px) scale(${vp.zoom})`,
    });
  }, [meta.name]);

  if (isLoading) {
    return (
      <div className="grid h-screen place-items-center bg-background">
        <LoadingState label="Loading shared map…" />
      </div>
    );
  }

  if (isError || !data) {
    return (
      <div className="grid h-screen place-items-center bg-background px-6">
        <EmptyState
          title="This shared map is no longer available"
          hint="The link may have been turned off or regenerated by its owner."
        />
      </div>
    );
  }

  return (
    <CanvasInteractionProvider value={interaction}>
      <div className="flex h-screen flex-col bg-background">
        <header className="flex shrink-0 items-center justify-between gap-3 border-b border-line bg-panel/60 px-4 py-2.5">
          <div className="flex min-w-0 items-center gap-2.5">
            <span className="truncate text-[14px] font-semibold">{data.name || "Untitled Map"}</span>
            <span className="shrink-0 rounded-full border border-line-strong bg-panel px-2 py-0.5 text-[10.5px] font-semibold uppercase tracking-[0.04em] text-faint">
              Shared · read-only
            </span>
          </div>
          <div className="flex shrink-0 items-center gap-2">
            <button
              type="button"
              onClick={() => fitView({ padding: 0.2, duration: 300 })}
              title="Fit view"
              className="grid h-8 w-8 place-items-center rounded-md border border-line-strong bg-panel text-foreground transition-colors hover:bg-panel2"
            >
              <Maximize className="h-4 w-4" />
            </button>
            <button
              type="button"
              onClick={onExportPng}
              title="Export PNG"
              className="grid h-8 w-8 place-items-center rounded-md border border-line-strong bg-panel text-foreground transition-colors hover:bg-panel2"
            >
              <ImageIcon className="h-4 w-4" />
            </button>
          </div>
        </header>

        <div ref={wrapperRef} className="relative min-h-0 flex-1">
          <ReactFlow
            nodes={nodes}
            edges={rfEdges}
            nodeTypes={nodeTypes}
            edgeTypes={edgeTypes}
            onNodesChange={onNodesChange}
            nodesDraggable={canDrag}
            nodesConnectable={false}
            elementsSelectable={false}
            edgesFocusable={false}
            // Nodes expose their handles as `type="source"` on all four sides and
            // edges target those source handles — Loose mode (same as the editor)
            // is required for those edges to render at all.
            connectionMode={ConnectionMode.Loose}
            deleteKeyCode={null}
            minZoom={0.1}
            maxZoom={2.5}
            proOptions={{ hideAttribution: true }}
            style={{ width: "100%", height: "100%" }}
            fitView
          >
            <Background gap={20} color="oklch(0.92 0.004 90)" />
            <Controls showInteractive={false} />
            <MiniMap
              pannable
              zoomable
              nodeColor={(n) => typeMeta((n.data as CanvasNodeData)?.elementType).color}
              nodeStrokeWidth={2}
              maskColor="oklch(0.97 0.003 95 / 0.6)"
            />
            <GroupsOverlay
              groups={groups}
              nodes={nodes}
              fontScale={fontScale}
              onDrag={canDrag ? moveGroupBy : undefined}
            />
          </ReactFlow>

          {nodes.length === 0 && (
            <div className="pointer-events-none absolute inset-0 flex items-center justify-center px-6 text-center text-[13px] text-faint">
              This map is empty.
            </div>
          )}
        </div>
      </div>
    </CanvasInteractionProvider>
  );
}
